spring.application.name=desafioCadastro


# Banco de dados

spring.datasource.url=jdbc:mysql://localhost:3306/sistemacadastropet
spring.datasource.username=usuario
spring.datasource.password=senha123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Executar scipts sql automaticamente
spring.sql.init.mode=ALWAYS
spring.jpa.defer-datasource-initialization=true

# Redis cache
spring.cache.type=REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Tempo de expiração do cache 1 hora
spring.cache.redis.time-to-live=3600000